// GENERATED by `node scripts/generateContract.mjs` from the Resume Master implementation — do not edit.
// Contract version 1.3.0. Types marked DERIVED were produced by executing the code that builds them.

export const CONTRACT_VERSION = "1.3.0";

export type Health = { ok: boolean; service: string; };

/** Assert `service`, never the status: an unknown path elsewhere may answer 200 with HTML. */
export type Version = { service: "resume-master"; version: string; commit: string | null; scorer: string; llmFormat: boolean; };

/** yearsOfExperience is THE AUTHORITY the claim guard enforces; a JD may not change it. */
export type Candidate = { fullName?: string; phone?: string; email?: string; linkedinUrl?: string; githubUrl?: string; location?: string; yearsOfExperience?: number | null; };

/** seniority is the candidate's own declaration: the document may use it and may not exceed it. */
export type JobProfile = { name: string; seniority?: "junior" | "mid" | "senior" | "executive" | null; keywords?: Array<string>; tools?: Array<string>; actionVerbs?: Array<string>; };

/** Skills and verbs the CANDIDATE asserts. Never a title, level or headline. */
export type Claims = { skills?: Array<string>; actionVerbs?: Array<string>; };

export type Job = { title: string; company?: string; category?: string; description?: string; stack?: string | null; };

export type GenerateRequest = { mode?: "GENERATE" | "A_PLUS"; domainModuleKey?: string; roleFamily?: string; domain?: string; candidate?: Candidate; profile?: JobProfile | null; claims?: Claims | null; employers?: Array<string>; job: Job; baseResumeText: string; options?: { includeSummary?: boolean; }; };

/** Only ever returned for a document that PASSED the claim guard. */
export type GenerateResponse = { html: string; domainModuleKey: string; claimCheck: { ok: true; inspected: ClaimInspection; }; usage: Array<UsageRecord>; };

export type EnhanceRequest = { resumeText: string; profile?: { name?: string; roleFamily?: string; domain?: string; }; selectedAdditions?: Array<string>; };

export type EnhanceResponse = { text: string; usage: Array<UsageRecord>; };

/** A PDF of at most 10 MB, base64-encoded. */
export type ParsePdfRequest = { pdfBase64: string; };

export type ParsePdfResponse = { text: string; chars: number; usage: Array<UsageRecord>; };

export type FormatRequest = { html: string; };

export type FormatResponse = { html: string; };

/** termWeights/synonyms are arrays of [key, value] pairs — JSON has no Map. Any other shape is a 400, never a silent unweighted score. */
export type AtsScoreRequest = { job: Job; resumeText: string; signalProfile?: Record<string, unknown>; domainProfile?: Record<string, unknown>; claims?: Claims | null; termWeights?: Array<Array<unknown>> | null; synonyms?: Array<Array<unknown>> | null; };

export type AtsScoreResponse = { report: AtsReport; };

/** `outcome` is the scorer's STATE, and `not_enough_signal` is its own state: the scorer declined for want of signal, `score` is null, and it is NOT a low score. `meaning` says so in words, for a caller that paraphrases. `scored` only when report.scorable is true and report.score is a number. */
export type McpAtsScoreResult = { outcome: "scored" | "not_enough_signal"; score: number | null; meaning: string; report: AtsReport; };

/** Print-ready HTML, not a PDF — there is no server-side PDF. The browser prints it. */
export type McpFormatResult = { html: string; contentType: "text/html"; howToGetPdf: string; };

export type JsonRpcErrorObject = { code: number; message: string; data?: unknown; };

/** Exactly one of result / error. A transport-level refusal (bad JSON, missing Accept) carries id null. */
export type JsonRpcResponse = { jsonrpc: "2.0"; id: number | string | null; result?: Record<string, unknown>; error?: JsonRpcErrorObject; };

/** `retryable` is present on every model-backed and auth error. ⛔ A non-retryable failure says so: `retryable: false` for an exhausted balance, a bad key or an unconfigured service. resume_claim_violation carries `violations` and NEVER the document. */
export type Error = { error: "invalid_request" | "invalid_json" | "unauthenticated" | "not_found" | "payload_too_large" | "resume_claim_violation" | "resume_claim_not_inspected" | "upstream_model_failure" | "model_unconfigured" | "auth_unconfigured" | "limit_exceeded" | "internal_error"; message?: string; retryable?: boolean; permanent?: boolean; violations?: Array<ClaimViolation>; usage?: Array<UsageRecord>; };

/** DERIVED BY EXECUTING @draft/ats-scorer scoreAtsLocally over 9 scenarios. Do not hand-edit — regenerate with `node scripts/generateContract.mjs`. No band is included: bands are each product's presentation decision. */
export type AtsReport = { source: string; score: null | number; scorable: boolean; decline_reasons: Array<string>; weighting: { applied: boolean; terms: number; }; seniority_cap: { applied: boolean; cap?: number; raw_score?: number; reason?: string; }; claimed_matches: Array<string>; tier1_matched: Array<string>; tier1_missing: Array<string>; competencies_matched: Array<string>; competencies_missing: Array<string>; action_verbs_matched: Array<string>; action_verbs_missing: Array<string>; action_verbs_generic: Array<string>; experience: { requiredYears: null | number; candidateYears: null | number; fit: boolean; summary: string; }; hard_constraint_misses: Array<string>; };

/** DERIVED BY EXECUTING src/model/anthropicCall.js callAnthropic over 3 scenarios. Do not hand-edit — regenerate with `node scripts/generateContract.mjs`. Counts, never content. Returned for every model call, failed calls included. */
export type UsageRecord = { purpose: string; model: string; success: boolean; input_tokens: number; output_tokens: number; cache_creation_input_tokens: number; cache_read_input_tokens: number; duration_ms: number; };

/** DERIVED BY EXECUTING the claim guard (checkResumeClaims) over 6 scenarios. Do not hand-edit — regenerate with `node scripts/generateContract.mjs`. `claimed`/`allowed` are numbers for a years violation and strings for a seniority one. */
export type ClaimViolation = { kind: string; claimed: number | string; allowed: number | string; evidence: Array<string>; message: string; };

/** DERIVED BY EXECUTING the claim guard over 6 scenarios. Do not hand-edit — regenerate with `node scripts/generateContract.mjs`. What the guard READ. documentChars > 0 on every returned document: the guard refuses to pass one it did not read. */
export type ClaimInspection = { documentChars: number; headlineRegion: string; headlineChars: number; seniorityCeilingKnown: boolean; };
