// Renders the contract — OpenAPI 3.1 JSON and TypeScript declarations — from the derived and
// declared halves. Deterministic: same source, same bytes, so --check can compare.
import crypto from "node:crypto";
import { DECLARED_SCHEMAS, ENDPOINTS, NOT_FOUND, CONTRACT_VERSION } from "./endpoints.js";
import { deriveSchemas, unknownItemPaths } from "./derived.js";

export const normaliseForHash = (text) => String(text).replace(/\r\n/g, "\n");
export const sha256 = (text) => crypto.createHash("sha256").update(normaliseForHash(text), "utf8").digest("hex");

export async function buildComponents() {
  const derived = await deriveSchemas();
  for (const [name, s] of Object.entries(derived)) {
    const gaps = unknownItemPaths(s);
    if (gaps.length) throw new Error(`derived ${name}: array item type never observed at ${gaps.join(", ")} — add a scenario in src/contract/derived.js`);
    if (name in DECLARED_SCHEMAS) throw new Error(`${name} is both declared and derived`);
  }
  return { ...DECLARED_SCHEMAS, ...derived };
}

export async function buildOpenApi() {
  const schemas = await buildComponents();
  const paths = {};
  for (const e of ENDPOINTS) {
    const op = {
      summary: `${e.cost === "metered" ? "[metered] " : e.cost === "free" ? "[free] " : ""}${e.method.toUpperCase()} ${e.path}`,
      ...(e.auth ? { security: [{ clientToken: [] }] } : { security: [] }),
      ...(e.request ? { requestBody: { required: true, content: { "application/json": { schema: e.request } } } } : {}),
      responses: Object.fromEntries(Object.entries(e.responses).map(([status, schema]) =>
        [status, { description: String(status), content: { "application/json": { schema } } }])),
    };
    (paths[e.path] ??= {})[e.method] = op;
  }
  return {
    openapi: "3.1.0",
    info: {
      title: "Resume Master API", version: CONTRACT_VERSION,
      description: "GENERATED by `node scripts/generateContract.mjs` — never hand-edited. Stateless: nothing a " +
        "caller sends is stored or logged. The claim guard runs on every generated document before it is returned. " +
        "See docs/API.md for the promises this contract carries.",
    },
    servers: [{ url: "https://resumemaster.one" }],
    "x-not-found": { description: "Any path not listed answers 404 with the Error schema — never a page.",
      responses: Object.fromEntries(Object.entries(NOT_FOUND).map(([s, schema]) => [s, { schema }])) },
    components: {
      securitySchemes: { clientToken: { type: "http", scheme: "bearer",
        description: "`rmk_<clientId>.<secret>`, one per client. The service stores only its sha256." } },
      schemas,
    },
    paths,
  };
}

export const renderJson = (doc) => JSON.stringify(doc, null, 2) + "\n";

/** A hash of the SHAPE only — descriptions and summaries stripped — so rewording is not a version. */
export function shapeHash(doc) {
  const strip = (v) => Array.isArray(v) ? v.map(strip) : v && typeof v === "object"
    ? Object.fromEntries(Object.entries(v).filter(([k]) => !["description", "summary", "info", "servers"].includes(k)).map(([k, x]) => [k, strip(x)]))
    : v;
  return sha256(JSON.stringify(strip(doc)));
}

// ── TypeScript ──────────────────────────────────────────────────────────────────────────────────
function ts(s) {
  if (!s || Object.keys(s).length === 0) return "unknown";
  if (s.$ref) return s.$ref.split("/").pop();
  if (s.anyOf) return s.anyOf.map(ts).join(" | ");
  if (s.enum) return s.enum.map(v => JSON.stringify(v)).join(" | ");
  const types = [].concat(s.type);
  return types.map(t => {
    if (t === "null") return "null";
    if (t === "array") return `Array<${ts(s.items)}>`;
    if (t === "object") {
      if (!s.properties) return "Record<string, unknown>";
      const req = new Set(s.required || []);
      return `{ ${Object.entries(s.properties).map(([k, v]) => `${k}${req.has(k) ? "" : "?"}: ${ts(v)};`).join(" ")} }`;
    }
    return t;
  }).join(" | ");
}

export async function buildTypeScript() {
  const doc = await buildOpenApi();
  const L = [
    "// GENERATED by `node scripts/generateContract.mjs` from the Resume Master implementation — do not edit.",
    `// Contract version ${CONTRACT_VERSION}. Types marked DERIVED were produced by executing the code that builds them.`,
    "",
    `export const CONTRACT_VERSION = ${JSON.stringify(CONTRACT_VERSION)};`,
    "",
  ];
  for (const [name, s] of Object.entries(doc.components.schemas)) {
    if (s.description) L.push(`/** ${s.description.replace(/\*\//g, "* /")} */`);
    L.push(`export type ${name} = ${ts(s)};`, "");
  }
  return L.join("\n");
}
