// Renders the contract — OpenAPI 3.1 JSON and TypeScript declarations — from the derived and
// declared halves. Deterministic: same source, same bytes, so --check can compare.
import crypto from "node:crypto";
import { DECLARED_SCHEMAS, ENDPOINTS, NOT_FOUND, CONTRACT_VERSION, MCP_TOOLS } from "./endpoints.js";
import { deriveSchemas, unknownItemPaths } from "./derived.js";

export const normaliseForHash = (text) => String(text).replace(/\r\n/g, "\n");
export const sha256 = (text) => crypto.createHash("sha256").update(normaliseForHash(text), "utf8").digest("hex");

export async function buildComponents() {
  const derived = await deriveSchemas();
  for (const [name, s] of Object.entries(derived)) {
    const gaps = unknownItemPaths(s);
    if (gaps.length) throw new Error(`derived ${name}: array item type never observed at ${gaps.join(", ")} — add a scenario in src/contract/derived.js`);
    if (name in DECLARED_SCHEMAS) throw new Error(`${name} is both declared and derived`);
  }
  return { ...DECLARED_SCHEMAS, ...derived };
}

export async function buildOpenApi() {
  const schemas = await buildComponents();
  const paths = {};
  for (const e of ENDPOINTS) {
    const op = {
      summary: `${e.cost === "metered" ? "[metered] " : e.cost === "free" ? "[free] " : ""}${e.method.toUpperCase()} ${e.path}`,
      ...(e.auth ? { security: [{ clientToken: [] }] } : { security: [] }),
      ...(e.request ? { requestBody: { required: true, content: { "application/json": { schema: e.request } } } } : {}),
      // A null schema is a declared body-less answer (MCP's 202) — no content, and the harness
      // checks that the real answer has none.
      responses: Object.fromEntries(Object.entries(e.responses).map(([status, schema]) =>
        [status, schema === null ? { description: `${status} — no body` }
          : { description: String(status), content: { "application/json": { schema } } }])),
    };
    (paths[e.path] ??= {})[e.method] = op;
  }
  return {
    openapi: "3.1.0",
    info: {
      title: "Resume Master API", version: CONTRACT_VERSION,
      description: "GENERATED by `node scripts/generateContract.mjs` — never hand-edited. Stateless: nothing a " +
        "caller sends is stored or logged. The claim guard runs on every generated document before it is returned. " +
        "See docs/API.md for the promises this contract carries.",
    },
    servers: [{ url: "https://resumemaster.one" }],
    "x-not-found": { description: "Any path not listed answers 404 with the Error schema — never a page.",
      responses: Object.fromEntries(Object.entries(NOT_FOUND).map(([s, schema]) => [s, { schema }])) },
    components: {
      securitySchemes: { clientToken: { type: "http", scheme: "bearer",
        description: "`rmk_<clientId>.<secret>`, one per client. The service stores only its sha256." } },
      schemas,
    },
    paths,
    "x-mcp": {
      description: "MCP (Model Context Protocol) server at POST /mcp — Streamable HTTP, stateless (no session), JSON " +
        "responses. Same client token as /v1. Tools are GENERATED here from the HTTP contract and served verbatim.",
      path: "/mcp",
      tools: buildMcpTools(schemas),
    },
  };
}

// ── MCP tools: GENERATED from the HTTP contract ─────────────────────────────────────────────────
//
// An MCP tool schema must be self-contained JSON Schema — no #/components to point into — so every
// $ref is resolved in place. inputSchema IS the tool's HTTP endpoint's request schema, resolved;
// outputSchema IS its declared result shape, resolved. Nothing about a tool's shape is written twice.
export function inlineRefs(schema, components, seen = []) {
  if (Array.isArray(schema)) return schema.map(s => inlineRefs(s, components, seen));
  if (!schema || typeof schema !== "object") return schema;
  if (schema.$ref) {
    const name = schema.$ref.split("/").pop();
    if (!components[name]) throw new Error(`$ref to undeclared schema ${name}`);
    if (seen.includes(name)) throw new Error(`recursive schema ${[...seen, name].join(" -> ")} cannot be inlined`);
    return inlineRefs(components[name], components, [...seen, name]);
  }
  return Object.fromEntries(Object.entries(schema).map(([k, v]) => [k, inlineRefs(v, components, seen)]));
}

export function buildMcpTools(components) {
  return MCP_TOOLS.map(t => {
    const endpoint = ENDPOINTS.find(e => `${e.method.toUpperCase()} ${e.path}` === t.endpoint);
    if (!endpoint?.request) throw new Error(`MCP tool ${t.name}: endpoint ${t.endpoint} has no request schema`);
    if (endpoint.cost !== "free") throw new Error(`MCP tool ${t.name}: ${t.endpoint} is ${endpoint.cost} — only free, deterministic tools ship in E1`);
    if (!components[t.result]) throw new Error(`MCP tool ${t.name}: result schema ${t.result} is not declared`);
    const inputSchema = inlineRefs(endpoint.request, components);
    const outputSchema = inlineRefs(components[t.result], components);
    for (const [k, s] of [["inputSchema", inputSchema], ["outputSchema", outputSchema]]) {
      if (s.type !== "object") throw new Error(`MCP tool ${t.name}: ${k} must be an object schema`);
    }
    return {
      name: t.name, title: t.title, description: t.description,
      inputSchema, outputSchema,
      annotations: { title: t.title, readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false },
      "x-endpoint": t.endpoint, "x-result": t.result, "x-cost": t.cost,
    };
  });
}

export const renderJson = (doc) => JSON.stringify(doc, null, 2) + "\n";

/** A hash of the SHAPE only — descriptions and summaries stripped — so rewording is not a version. */
export function shapeHash(doc) {
  const strip = (v) => Array.isArray(v) ? v.map(strip) : v && typeof v === "object"
    ? Object.fromEntries(Object.entries(v).filter(([k]) => !["description", "summary", "info", "servers"].includes(k)).map(([k, x]) => [k, strip(x)]))
    : v;
  return sha256(JSON.stringify(strip(doc)));
}

// ── TypeScript ──────────────────────────────────────────────────────────────────────────────────
function ts(s) {
  if (!s || Object.keys(s).length === 0) return "unknown";
  if (s.$ref) return s.$ref.split("/").pop();
  if (s.anyOf) return s.anyOf.map(ts).join(" | ");
  if (s.enum) return s.enum.map(v => JSON.stringify(v)).join(" | ");
  const types = [].concat(s.type);
  return types.map(t => {
    if (t === "null") return "null";
    if (t === "array") return `Array<${ts(s.items)}>`;
    if (t === "object") {
      if (!s.properties) return "Record<string, unknown>";
      const req = new Set(s.required || []);
      return `{ ${Object.entries(s.properties).map(([k, v]) => `${k}${req.has(k) ? "" : "?"}: ${ts(v)};`).join(" ")} }`;
    }
    return t;
  }).join(" | ");
}

export async function buildTypeScript() {
  const doc = await buildOpenApi();
  const L = [
    "// GENERATED by `node scripts/generateContract.mjs` from the Resume Master implementation — do not edit.",
    `// Contract version ${CONTRACT_VERSION}. Types marked DERIVED were produced by executing the code that builds them.`,
    "",
    `export const CONTRACT_VERSION = ${JSON.stringify(CONTRACT_VERSION)};`,
    "",
  ];
  for (const [name, s] of Object.entries(doc.components.schemas)) {
    if (s.description) L.push(`/** ${s.description.replace(/\*\//g, "* /")} */`);
    L.push(`export type ${name} = ${ts(s)};`, "");
  }
  return L.join("\n");
}
