// client/src/pages/marketing/TermsPage.jsx
import { useTheme } from "../../styles/theme.jsx";
import ScrollDock from "../../components/ScrollDock.jsx";
import { Footer } from "../../components/Footer.jsx";

const SECTIONS = [
  {
    title: "Acceptance of Terms",
    body: `By accessing or using Resume Master, you agree to be bound by these Terms of Service. If you do not agree to these terms, do not use the service. We reserve the right to update these terms at any time; continued use of the service constitutes acceptance of updated terms.`,
  },
  {
    title: "Use of Service",
    body: `Resume Master is provided for personal, non-commercial use. You may use the service to generate and manage resumes, search for job listings, and track applications. You may not: resell or redistribute the service; use the service to generate false, misleading, or fraudulent information; attempt to reverse-engineer or exploit the platform; or use automated means to access the service outside of provided APIs.`,
  },
  {
    title: "Account Responsibilities",
    body: `You are responsible for maintaining the confidentiality of your account credentials and for all activity under your account. You must provide accurate information during registration. You may not share accounts or allow third-party access to your account. Notify us immediately if you suspect unauthorized access.`,
  },
  {
    title: "Intellectual Property",
    body: `Resume content you provide remains yours. Resumes generated by Resume Master on your behalf are yours to use freely. The Resume Master platform, interface, branding, and underlying software are our intellectual property and may not be copied, modified, or redistributed without written permission.`,
  },
  {
    title: "Limitation of Liability",
    body: `Resume Master is provided "as is" without warranty of any kind. We do not guarantee that use of the service will result in employment or interview invitations. We are not liable for any direct, indirect, incidental, or consequential damages arising from your use of the service, including but not limited to data loss, employment outcomes, or service interruptions.`,
  },
  {
    title: "Changes to Terms",
    body: `We may modify these terms at any time. Material changes will be announced via the platform. Your continued use of the service after changes take effect constitutes your acceptance of the revised terms.`,
  },
  {
    title: "Contact",
    body: `Questions about these terms? Use the contact form at /contact.`,
  },
];

export function TermsPage() {
  const { theme } = useTheme();
  return (
    <div className="scroll-dock-page" style={{ minHeight: "100vh", display: "flex", flexDirection: "column",
                  background: theme.bg, color: theme.text,
                  fontFamily: "'DM Sans', system-ui, sans-serif" }}>
      <ScrollDock variant="marketing" />
      <main style={{ flex: 1, maxWidth: 720, margin: "0 auto", padding: "64px 24px" }}>
        <h1 style={{ fontSize: "clamp(28px, 4vw, 44px)", fontWeight: 900, letterSpacing: "-1px",
                      color: theme.text, marginBottom: 8, lineHeight: 1.1,
                      fontFamily: "'Barlow Condensed', 'DM Sans', system-ui" }}>
          Terms of Service
        </h1>
        <p style={{ fontSize: 13, color: theme.textDim, marginBottom: 48 }}>
          Last updated: April 2025
        </p>
        {SECTIONS.map((s, i) => (
          <div key={i} style={{ marginBottom: 40 }}>
            <h2 style={{ fontSize: 18, fontWeight: 800, color: theme.text, marginBottom: 12 }}>
              {s.title}
            </h2>
            <p style={{ fontSize: 14, color: theme.textMuted, lineHeight: 1.8, margin: 0 }}>
              {s.body}
            </p>
          </div>
        ))}
      </main>
      <Footer/>
    </div>
  );
}
